name: Update gist with new hitokoto

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 10 * * *"
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: 2e1f9d2e577fb272df979f1c6c6a83c8
      CATEGORY: ''
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out
      uses: actions/checkout@v2

    - name: Update gist
      run: go run .
